/**********************************************************************************
Developed by: Freeway Consulting
Author: Hector Diaz
Project:  "Edenred" 
Description: .
---------------------------------------------------------------------------------
Version       Date         Author                   Description
------ ---------- ---------------------------------------------------------------
1.0       20-Abril-2020      Hector Diaz               Initial version
*************************************************************************************/
public class AffiliateCallWS_cls{

}