/**********************************************************************************
Developed by: Freeway Consulting
Author: Hector Diaz
Project:  "Edenred" 
Description: .
---------------------------------------------------------------------------------
Version       Date         Author                   Description
------ ---------- ---------------------------------------------------------------
1.0       18-Mayo-2020      Hector Diaz               Initial version
*************************************************************************************/
@isTest
public class MerchantService_tst {

    @isTest static void testMethod1(){         
    }
}